### PR TITLE
Update pfsense_rule.py with invert rule

### PR DESCRIPTION
**Pull request by madgics**
This feature allows to invert a rule with "!" .
Exemple:
  - name: "Add invert rule"
    pfsense_rule:
      name: 'Accept all connection except for 192.168.1.100 destination'
      action: pass
      interface: lan
      ipprotocol: inet
      protocol: udp
      source: any
      destination: 192.168.1.100:any:!
      state: present

### CODE REVIEW

**Comment by opoplawski** [comment]
I would prefer a '!192.168.1.100:any' syntax - seems more intuitive and more closely matches the GUI display.  Any reason not to?

**Comment by madgics** [comment]
Not any reason to not do that, it's was simple to do but your proposition seem to be more comprehensive

**Comment by opoplawski** [comment]
Thanks, looks good.  Please rebase against current master and squash to a single commit.

**Comment by opoplawski** [comment]
I've added this now.  Thanks.

**Pull request closed without merging**
