### PR TITLE
Add Module for syslog settings

### PR DESCRIPTION
**Pull request by coffeelover**
This module is for controlling log settings (syslog entry in config.xml).

Currently not able to create a test.

When renaming `tests/unit` to `tests/unit` and running `ansible-test units`, I get various ModuleNotFoundError.
(I already installed `community.internal_test_tools`)

I would like to add tests if the problem could be solved.

### CODE REVIEW

**Comment by f-bor** [comment]
Thank you for your contribution.

You don't need to split your module between 2 files. You can put all your code in library/pfsense_log_settings.py. We need two files when a module can be called from another module (aggregate kind). It is for users that need to do multiple changes in one module call (change aliases, change separators and change rules for example).

Also don't forget to add your module to readme.md.

To setup unit test, you should run ./misc/setup_units_tests once and then use ./misc/pytest to run the tests. It should at least work for the existing tests. You can pass args to the script, which are then passed to pytest (like ./misc/pytest -k log_settings).

**Comment by coffeelover** [comment]
Great! Will refactor the code and add tests. Thank you!

**Comment by coffeelover** [comment]
I began adding tests, some are running fine.
I have one problem which i don't understand enough to fix it :) Perhaps you have a idea?
Two tags in config.xml are problematic: `syslog/format` and `syslog/filter`. I remapped these to `logformat` and `logfilter` in the module and undo the mapping when writing the xml. But the tests seem to check if the dictionary key maps to the xml tag, which is not the case. I don't want to alter the TestPFSenseModule class.
Do you have a hint for me?

**Comment by f-bor** [comment]
There is a parameter in check_param_bool for this (xml_field). In the end, your calls should mean something like this:
```
self.check_param_bool (syslog, syslog_elt, 'logformat', xml_field='format')
self.check_param_bool (syslog, syslog_elt, 'logfilter', xml_field='filter')

```

**Comment by coffeelover** [comment]
OK, my tests run successfully on my local machine, but not on travis. What could be the cause?

**Comment by coffeelover** [comment]
OK, I'm done with development. Travis is not failing on anything log_settings related.
@opoplawski Is there anything left or are you able to merge my module?

**Comment by opoplawski** [comment]
@coffeelover Jan - thanks for this.  I'm afraid I'm pretty swamped and won't be able to look at this soon.  Some quick comments:

- can you trim down the fixture file to something that's only relevant to your tests?  I'm wondering if we should combine fixtures but that's something for later.
- go ahead and squash your commits
- we'll try to get the tests working soon

**Comment by coffeelover** [comment]
OK, fixture is trimmed down (I still need interfaces/vips for `sourceip`-Setting)
Commits are squashed (isn't that something that can be set as project/pull-request setting like 'Allow Squash'?)

But let me thank you for your great work, it was really quite easy to follow your code and implement a module :)

**Comment by f-bor** [comment]
Thank you, for both your contribution and kind words.

A syslog module was really needed and I'll use your module at work when I have time to write the playbook.

You should add a link in the main readme.md to [the wiki for your module](https://github.com/opoplawski/ansible-pfsense/wiki/pfsense_log_settings). Besides that, it's ok to be merged for me.

**Comment by coffeelover** [comment]
@f-bor I added a link to the wiki. Should i again squash the commits or is it ok for you?

**Comment by f-bor** [comment]
it's ok for me :)

**Pull request merged**
